products/urls.py
from django.urls import path
from .views import product_create_list_view, product_add_list_view, ProductUpdateView, ProductSellView, ProductBuyView, product_post_buy, ProductCancelView


app_name = 'products'

urlpatterns =[
    path('', product_create_list_view, name='main-product-view'),
    path('add/', product_add_list_view, name='product-add-view'),
    path('<pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('<pk>/sell/', ProductSellView.as_view(), name='product-sell'),
    path('<pk>/buy/', ProductBuyView.as_view(), name='product-buy'),
    path('success/', product_post_buy, name='product-buy-success'),
    path('<pk>/cancel/', ProductCancelView.as_view(), name='product-cancel'),
]

shopifyChallenge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home-view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('products/', include('products.urls', namespace='products')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from django.db import models
from .utils import get_random_id
from django.template.defaultfilters import slugify
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from profiles.models import Profile
from django.contrib.auth.decorators import login_required
# Create your models here.

class Product(models.Model):
    image = models.ImageField(upload_to='products', validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    name = models.CharField(default='product', max_length = 200)
    description = models.TextField(default="no bio", max_length=300,blank=True)
    tags = models.TextField(default="no bio", max_length=300,blank=True)
    slug = models.SlugField(unique=True, blank=True)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='products')
    owned = 'owned'
    listed = 'listed'
    status_choice = [(owned, 'Owned'), (listed, 'Listed')]

    updated = models.DateTimeField(auto_now=True)
    created= models.DateTimeField(auto_now_add = True)
    price = models.IntegerField(default=1)
    status = models.CharField(max_length = 9,choices = status_choice, default = 1)

    def __str__(self):
        return f"{self.name}"
        

    def save(self, *args, **kwargs):
        ex = True
        to_slug = "w"
        while ex:
            to_slug = slugify(to_slug + " " +str(get_random_id()))
            ex = Product.objects.filter(slug=to_slug).exists()
        self.slug = to_slug
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)

products/forms.py
from django import forms
from .models import Product

class ProductModelForm(forms.ModelForm):
    # content = forms.CharField(widget=forms.Textarea(attrs={'rows':5}))
    tags = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':5}))
    class Meta:
        model = Product
        fields = ('name', 'image', 'description', 'tags', 'price', 'status')

class ProductUpdateForm(forms.ModelForm):
    # content = forms.CharField(widget=forms.Textarea(attrs={'rows':5}))
    tags = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':5}))
    class Meta:
        model = Product
        fields = ('name', 'description', 'tags', 'price')

class ProductSellForm(forms.ModelForm):
    # content = forms.CharField(widget=forms.Textarea(attrs={'rows':5}))
    class Meta:
        model = Product
        fields = ('price', )

class ProductBuyForm(forms.ModelForm):
    # content = forms.CharField(widget=forms.Textarea(attrs={'rows':5}))
    class Meta:
        model = Product
        fields = ()

products/views.py
from django.shortcuts import render
from .models import Product
from profiles.models import Profile
from .forms import ProductModelForm, ProductUpdateForm, ProductSellForm, ProductBuyForm
from django.urls import reverse_lazy
from django.views.generic import UpdateView, ListView
from django.db.models import Q

# Create your views here.


def product_create_list_view(request):
    qs = Product.objects.all()
    query=''
    if 'q' in request.GET:
        query = request.GET.get('q')
        queryset = (Q(tags__icontains=query))
        qs = Product.objects.filter(queryset).distinct()
    
    profile = Profile.objects.get(user=request.user)

    context = {
        'qs': qs,
        'profile': profile,
        'query': query,
    }

    return render(request, 'products/product_list.html', context)


def product_add_list_view(request):
    qs = Product.objects.all()
    profile = Profile.objects.get(user=request.user)

    # Product form
    p_form = ProductModelForm()
    post_add = False

    if 'submit_p_form' in request.POST:
        p_form = ProductModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instance = p_form.save(commit=False)
            instance.owner = profile
            instance.save()
            p_form = ProductModelForm()
            post_add = True

    context = {
        'qs': qs,
        'profile': profile,
        'p_form': p_form,
        'post_add': post_add,
    }

    return render(request, 'products/add.html', context)


class ProductUpdateView(UpdateView):
    form_class = ProductUpdateForm
    model = Product
    template_name = 'products/update.html'
    success_url = reverse_lazy('products:main-product-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if not form.instance.owner == profile:
            form.add_error(None, 'You are not the owner of the product')
            return super().form_invalid(form)
        if form.instance.status == "listed":
            form.add_error(
                None, 'You must cancel the listing of the product first')
            return super().form_invalid(form)
        else:
            return super().form_valid(form)  # if valid update the form


class ProductSellView(UpdateView):
    form_class = ProductSellForm
    model = Product
    template_name = 'products/sell.html'
    success_url = reverse_lazy('products:main-product-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        print(form.instance.status)
        if not form.instance.owner == profile:
            form.add_error(None, 'You are not the owner of the product')
            return super().form_invalid(form)
        else:
            form.instance.status = "listed"
            return super().form_valid(form)  # if valid update the form


class ProductCancelView(UpdateView):
    form_class = ProductBuyForm
    model = Product
    template_name = 'products/cancel.html'
    success_url = reverse_lazy('products:main-product-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if not form.instance.owner == profile:
            form.add_error(None, 'You are not the owner of the product')
            return super().form_invalid(form)
        else:
            form.instance.status = "owned"
            return super().form_valid(form)  # if valid update the form


class ProductBuyView(UpdateView):
    form_class = ProductBuyForm
    model = Product
    template_name = 'products/buy.html'
    success_url = reverse_lazy('products:product-buy-success')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.owner == profile:
            form.add_error(None, 'You are the owner of the product')
            return super().form_invalid(form)
        if form.instance.price > profile.credit:
            form.add_error(None, 'You don\'t have enough money')
            return super().form_invalid(form)
        else:
            print(form.instance.owner.credit)
            form.instance.owner.credit = form.instance.owner.credit + form.instance.price
            form.instance.owner.save()
            form.instance.owner = profile
            form.instance.status = "owned"
            profile.credit = profile.credit - form.instance.price
            profile.save()
            return super().form_valid(form)  # if valid update the form


def product_post_buy(request):
    qs = Product.objects.all()
    profile = Profile.objects.get(user=request.user)

    context = {
        'qs': qs,
        'profile': profile,
    }

    return render(request, 'products/buy_success.html', context)

products/templates/products/add.html
{% extends 'base.html' %}

{% block title%}
Add Image
{% endblock title%}

{% block content%}

<div class="ui grid">
    <div class="row">
        {% if post_add %}
        <div class="ui green message">Posted</div>
        {% endif %}
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{p_form}}
            <button type='submit' class='ui button positive subbutton' name="submit_p_form">Add Product</button>
            <form>
    </div>
</div>



{% endblock content%}

products/templates/products/buy.html
{% extends 'base.html' %}

{% block title %}
Sell Product
{% endblock title %}

{% block content %}

    <div class= 'ui segment'>
        <h3>Buy Product</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            Buy {{form.instance.name}} for {{form.instance.price}} credit?<br>
            <br>
            {{form}}
            <button type ='submit' class ="ui button primary mt-5">Confirm</button>
        </form>
        <a href="/products/" class="item">
            <button class ="ui button primary mt-5">Cancel</button>
        </a>
    </div>
{% endblock content %}

products/templates/products/buy_success.html
{% extends 'base.html' %}

{% block title%}
Success!
{% endblock title%}

{% block content%}

<div class="ui grid">
    <div class="row">
        Successfully bought the product. <br>
        Remained credit: {{profile.credit}}
    </div>
</div>



{% endblock content%}

products/templates/products/cancel.html
{% extends 'base.html' %}

{% block title %}
Sell Product
{% endblock title %}

{% block content %}

    <div class= 'ui segment'>
        <h3>Cancel product listing</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            Cancel the listing of this product? <br>
            <br>
            {{form}}
            <button type ='submit' class ="ui button primary mt-5">Confirm</button>
        </form>
        <a href="/products/" class="item">
            <button class ="ui button primary mt-5">Cancel</button>
        </a>
    </div>
{% endblock content %}

products/templates/products/confirm_del.html
{% extends 'base.html' %}

{% block title %}
delete post
{% endblock title %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if 'warning' in message.tags %}
            <div class='ui negative message'>
                <div class="header">
                    {{message}}
                </div>
            </div>
        {% endif %}
    {% endfor %}

{% endif %}
    {% if not messages %}
    <div class="ui segment">
        <h3>Delete Post?</h3>
        <form action="" method ="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete the post?</p>
            <button type='submit'>Delete</button>
    </div>
    {% endif %}

{% endblock content %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block title%}
Products
{% endblock title%}

{% block content %}
{% if query %}
    <div class='searchr'>
        Search result for <b>{{query}}</b>.
    </div>
{% endif %}
<div class="ui grid">
    <!-- <form method='GET' action="">
        <input type="text" name="search" id = "search" placeholder="Search posts"/>
        <input type="submit"  value="Search"/>
        </form> -->

    <form action="" method="GET">
        <div class="ui action left icon input searchb">
            <input class="prompt" type="search" name='q' placeholder="Search for an image...">
            <i class="search icon"></i>
            <button type='submit' class="ui button">Search</button>
        </div>
    </form>

    <div class="row">
        <div class="seven wide column">
            {% for obj in qs %}
            {% if not forloop.counter|divisibleby:2 %}
            {% csrf_token %}
            <div class="ui fluid card gameblock">
                <input type="hidden" name="game_id" value={{obj.id}}>
                <div class="fifty">
                    <div class="fifty-l">
                        <div class="content imgtext">
                            <h3>{{obj.name}} </h3>
                            Description: {{obj.description}} <br>
                            Tags: {{obj.tags}} <br>
                            {% if obj.status == "listed" %}
                            For sale: Yes <br>
                            Price: {{obj.price}} <br>
                            {% else %}
                            For sale: No <br>
                            {% endif %}
                        </div>
                        <div class="right floated gamebutton">
                            {% if not obj.owner == profile %}
                            {% if obj.status == "listed" %}
                            <a href="{% url 'products:product-buy' obj.pk %}"><button
                                    class="ui button bwhite-lg">Buy</button></a>
                            {% endif %}
                            {% else %}
                            {% if obj.status == "owned" %}
                            <a href="{% url 'products:product-sell' obj.pk %}"><button
                                    class="ui button bwhite-lg">Sell</button></a>
                            <a href="{% url 'products:product-update' obj.pk %}"><button
                                    class="ui button bwhite-lg">Update</button></a>
                            {% else %}
                            <a href="{% url 'products:product-cancel' obj.pk %}"><button
                                    class="ui button bwhite-lg">Cancel Listing</button></a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="fifty-r">
                        <a href="{{obj.image.url}}" target="_blank">
                            <div class="imgCard">
                                <img src="{{obj.image.url}}">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
        </div>
        <div class="seven wide column">
            {% for obj in qs %}
            {% if forloop.counter|divisibleby:2 %}
            {% csrf_token %}
            <div class="ui fluid card gameblock">
                <input type="hidden" name="game_id" value={{obj.id}}>
                <div class="fifty">
                    <div class="fifty-l">
                        <div class="content imgtext">
                            <h3>{{obj.name}} </h3>
                            Description: {{obj.description}} <br>
                            Tags: {{obj.tags}} <br>
                            {% if obj.status == "listed" %}
                            For sale: Yes <br>
                            Price: {{obj.price}} <br>
                            {% else %}
                            For sale: No <br>
                            {% endif %}
                        </div>
                        <div class="right floated gamebutton">
                            {% if not obj.owner == profile %}
                            {% if obj.status == "listed" %}
                            <a href="{% url 'products:product-buy' obj.pk %}"><button
                                    class="ui button bwhite-lg">Buy</button></a>
                            {% endif %}
                            {% else %}
                            {% if obj.status == "owned" %}
                            <a href="{% url 'products:product-sell' obj.pk %}"><button
                                    class="ui button bwhite-lg">Sell</button></a>
                            <a href="{% url 'products:product-update' obj.pk %}"><button
                                    class="ui button bwhite-lg">Update</button></a>
                            {% else %}
                            <a href="{% url 'products:product-cancel' obj.pk %}"><button
                                    class="ui button bwhite-lg">Cancel Listing</button></a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="fifty-r">
                        <a href="{{obj.image.url}}" target="_blank">
                            <div class="imgCard">
                                <img src="{{obj.image.url}}">
                            </div>
                        </a>
                    </div>
                </div>
            </div>
            <br>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}

products/templates/products/sell.html
{% extends 'base.html' %}

{% block title %}
Sell Product
{% endblock title %}

{% block content %}

    <div class= 'ui segment'>
        <h3>Sell Product</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            Change the status to listed to put the image up for sale. <br>
            <br>
            {{form}}
            <button type ='submit' class ="ui button primary mt-5">Confirm</button>
        </form>
        <a href="/products/" class="item">
            <button class ="ui button primary mt-5">Cancel</button>
        </a>
    </div>
{% endblock content %}

products/templates/products/update.html
{% extends 'base.html' %}

{% block title %}
Update Product
{% endblock title %}

{% block content %}

    <div class= 'ui segment'>
        <h3>Update Product</h3>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button type ='submit' class ="ui button primary mt-5">Update</button>
        </form>
    </div>
{% endblock content %}